### ISSUE TITLE
Test "staphopia-sccmec" 

### ISSUE THREAD

**Issue by ajkarloss** [NorwegianVeterinaryInstitute/irida-plugin-sccmecfinder#7]
staphopia-sccmec looks like a good tool for finding sccmec in MRSA. 

https://github.com/staphopia/staphopia-sccmec

It installable and works fine. 

Ran 5 samples through the tool and sent the results to Marianne to check if it provides everything she needs

**Comment by 01schau** [comment]
FYI: 
"The **Staphopia analysis pipline will no longer be supported**, instead you should use [Bactopia](https://bactopia.github.io/). Bactopia is the successor to Staphopia and is still being actively supported and developed. Even better Staphopia is built into Bactopia, so you can easily make use S. aureus specific analyses."

https://staphopia.github.io/

**Comment by ajkarloss** [comment]
Tested and the results are not correct (missing results compare to CGE SCCMecFinder).
